### ISSUE TITLE
Validations rely on transactions being built by cardano-cli

### ISSUE THREAD

**Issue by DavidTranDucVL** [vacuumlabs/cardano-hw-cli#52] opened 2021-02-22 18:29 UTC
See: https://github.com/vacuumlabs/cardano-hw-cli/pull/42#discussion_r575215602 and https://github.com/vacuumlabs/cardano-hw-cli/pull/42#discussion_r574479457

**Comment by abobolaispool** [comment] 2021-08-21 07:13
I am getting this error

cardano-cli transaction assemble \
> --tx-body-file tx-pool.raw \
> --witness-file node.witness \
> --witness-file stake.witness \
> --witness-file payment.witness \
Invalid argument ` '
Did you mean this?
-h
Usage: cardano-cli transaction assemble --tx-body-file FILE
(--witness-file FILE) --out-file FILE

**Comment by gabrielKerekes** [comment] 2021-08-23 05:40
@abobolaispool have you been able to resolve the issue? I think the problem is just the trailing `\` in the last line of your command and some missing arguments? However, just to clarify, this is the repository for **cardano-hw-cli** and you are using [**cardano-cli**](https://github.com/input-output-hk/cardano-node/tree/master/cardano-cli) so you might rather want to look around there. I would also suggest creating your own issue rather than "hijacking" unrelated, existing issues/PRs.

**Comment by davidmisiak** [comment] 2022-03-14 12:35
Regarding the original issue by @DavidTranDucVL, I believe this is resolved by cardano-hw-interop-lib parsing the tx (all buffer sizes and other structural properties of the tx should be validated by interop-lib).

**Closed** 2022-03-14 12:36 UTC
