### ISSUE TITLE
cardano-hw-cli returns no errocode

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/cardano-hw-cli#23] opened 2020-12-25 12:14 UTC
Running a simple:

```
cardano-hw-cli shelley address key-gen \
--path 1852H/1815H/0H/0/0 \
--verification-key-file payment.vkey \
--hw-signing-file payment.hwsfile
```

command without any hw wallet attached displays an error message, but the returncode is still 0. so, hard to catch some errors. please exit with an errorcode.

also the given errormessage is not really a good one:
`Error: payload.map is not a function
`

please return something more useful in this case like:
`Error: no compatible hardware wallet found
`

The current workaround is to capture the error messages and parse them in the scripts using cardano-hw-cli to determine if an error occured.

**Comment by DavidTranDucVL** [comment] 2021-01-11 15:53
I'm not able to reproduce the problem. When I don't have any device connected I'm getting `Error occured while trying to find hw transport, make sure Ledger or Trezor is connected to you computer` as intended.

I changed errors to return with 1 instead of 0.

**Comment by gitmachtl** [comment] 2021-01-11 16:24
Hi, yes a written error is returned to the StdErr device, but the returncode was zero. As a workaround a parsed the Textoutput to check if there is an error, but when you now changed the return to 1 instead of zero if an error occur, than all is good. :smiley:

**Comment by DavidTranDucVL** [comment] 2021-01-20 01:45
Resolved in https://github.com/vacuumlabs/cardano-hw-cli/pull/37

**Closed by DavidTranDucVL** 2021-01-20 01:45 UTC
Labels: bug
